[2024-05-24T00:22:23.839+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T00:22:23.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.load_Sea_Level_Data manual__2024-05-24T00:22:18.838494+00:00 [queued]>
[2024-05-24T00:22:23.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.load_Sea_Level_Data manual__2024-05-24T00:22:18.838494+00:00 [queued]>
[2024-05-24T00:22:23.852+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T00:22:23.857+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_Sea_Level_Data> on 2024-05-24 00:22:18.838494+00:00
[2024-05-24T00:22:23.860+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=308) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T00:22:23.860+0000] {standard_task_runner.py:63} INFO - Started process 314 to run task
[2024-05-24T00:22:23.861+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'load_Sea_Level_Data', 'manual__2024-05-24T00:22:18.838494+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpqww58ktv']
[2024-05-24T00:22:23.862+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask load_Sea_Level_Data
[2024-05-24T00:22:23.880+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.load_Sea_Level_Data manual__2024-05-24T00:22:18.838494+00:00 [running]> on host 7f18484bb9a3
[2024-05-24T00:22:23.919+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='load_Sea_Level_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T00:22:18.838494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T00:22:18.838494+00:00'
[2024-05-24T00:22:23.919+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T00:22:23.920+0000] {log.py:232} WARNING - [2024-05-24 00:22:23,920] [INFO] - Database CombinedDataset.sqlite did not exist and was created.
[2024-05-24T00:22:23.920+0000] {base_logger.py:19} INFO - Database CombinedDataset.sqlite did not exist and was created.
[2024-05-24T00:22:23.973+0000] {log.py:232} WARNING - [2024-05-24 00:22:23,973] [INFO] - Data from ./data/transformed/Solar_Flare_Data.csv loaded into Solar_Flare_Data table in CombinedDataset.sqlite database.
[2024-05-24T00:22:23.973+0000] {base_logger.py:19} INFO - Data from ./data/transformed/Solar_Flare_Data.csv loaded into Solar_Flare_Data table in CombinedDataset.sqlite database.
[2024-05-24T00:22:23.973+0000] {log.py:232} WARNING - [2024-05-24 00:22:23,973] [INFO] - Connection to CombinedDataset.sqlite closed.
[2024-05-24T00:22:23.973+0000] {base_logger.py:19} INFO - Connection to CombinedDataset.sqlite closed.
[2024-05-24T00:22:23.974+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T00:22:23.974+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T00:22:23.979+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=load_Sea_Level_Data, run_id=manual__2024-05-24T00:22:18.838494+00:00, execution_date=20240524T002218, start_date=20240524T002223, end_date=20240524T002223
[2024-05-24T00:22:23.993+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T00:22:24.002+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T00:22:24.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
