[2024-05-24T00:18:34.698+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T00:18:34.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.load_Temperature_Data manual__2024-05-24T00:18:30.441951+00:00 [queued]>
[2024-05-24T00:18:34.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.load_Temperature_Data manual__2024-05-24T00:18:30.441951+00:00 [queued]>
[2024-05-24T00:18:34.710+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T00:18:34.715+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_Temperature_Data> on 2024-05-24 00:18:30.441951+00:00
[2024-05-24T00:18:34.718+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T00:18:34.719+0000] {standard_task_runner.py:63} INFO - Started process 149 to run task
[2024-05-24T00:18:34.719+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'load_Temperature_Data', 'manual__2024-05-24T00:18:30.441951+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpkyvlmiyv']
[2024-05-24T00:18:34.720+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask load_Temperature_Data
[2024-05-24T00:18:34.739+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.load_Temperature_Data manual__2024-05-24T00:18:30.441951+00:00 [running]> on host 7f18484bb9a3
[2024-05-24T00:18:34.771+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='load_Temperature_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T00:18:30.441951+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T00:18:30.441951+00:00'
[2024-05-24T00:18:34.772+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T00:18:34.772+0000] {log.py:232} WARNING - [2024-05-24 00:18:34,772] [INFO] - Database CombinedDataset.sqlite exists. Connected successfully.
[2024-05-24T00:18:34.772+0000] {base_logger.py:19} INFO - Database CombinedDataset.sqlite exists. Connected successfully.
[2024-05-24T00:18:34.811+0000] {log.py:232} WARNING - [2024-05-24 00:18:34,811] [INFO] - Data from ./data/transformed/Solar_Flare_Data.csv loaded into Solar_Flare_Data table in CombinedDataset.sqlite database.
[2024-05-24T00:18:34.811+0000] {base_logger.py:19} INFO - Data from ./data/transformed/Solar_Flare_Data.csv loaded into Solar_Flare_Data table in CombinedDataset.sqlite database.
[2024-05-24T00:18:34.812+0000] {log.py:232} WARNING - [2024-05-24 00:18:34,812] [INFO] - Connection to CombinedDataset.sqlite closed.
[2024-05-24T00:18:34.812+0000] {base_logger.py:19} INFO - Connection to CombinedDataset.sqlite closed.
[2024-05-24T00:18:34.812+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T00:18:34.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T00:18:34.816+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=load_Temperature_Data, run_id=manual__2024-05-24T00:18:30.441951+00:00, execution_date=20240524T001830, start_date=20240524T001834, end_date=20240524T001834
[2024-05-24T00:18:34.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T00:18:34.857+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T00:18:34.858+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
